### ISSUE TITLE
KeyError: 'num_layers'

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#109]
After updating to model52 and trying to launch on master (afdb864713a0200ea403fcbd60387e7f2789f689) I get the following error.

```
$ ./start_bayou.sh
/build_scripts/out$ 2017-10-19 18:13:57.573:INFO::main: Logging initialized @12205ms to org.eclipse.jetty.util.log.StdErrLog
2017-10-19 18:13:58.237:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2017-10-19 18:13:58.671:INFO:oejs.AbstractConnector:main: Started ServerConnector@75c072cb{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-10-19 18:13:58.672:INFO:oejs.Server:main: Started @13305ms
2017-10-19 18:14:17.958477: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-19 18:14:17.958537: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-19 18:14:17.958555: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
===================================
    Loading Model. Please Wait.    
===================================
Traceback (most recent call last):
  File "/home/barnett/workDev/bayou/repos/github/capergroup/bayou/master/tool_files/build_scripts/out/python/bayou/server/ast_server.py", line 176, in <module>
    bp = BayesianPredictor(args.save_dir, sess)  # create a predictor that can generates ASTs from evidence
  File "/home/barnett/workDev/bayou/repos/github/capergroup/bayou/master/tool_files/build_scripts/out/python/bayou/experiments/low_level_evidences/infer.py", line 39, in __init__
    config = read_config(json.load(f), chars_vocab=True)
  File "/home/barnett/workDev/bayou/repos/github/capergroup/bayou/master/tool_files/build_scripts/out/python/bayou/experiments/low_level_evidences/utils.py", line 59, in read_config
    config.evidence = bayou.experiments.low_level_evidences.evidence.Evidence.read_config(js['evidence'], chars_vocab)
  File "/home/barnett/workDev/bayou/repos/github/capergroup/bayou/master/tool_files/build_scripts/out/python/bayou/experiments/low_level_evidences/evidence.py", line 51, in read_config
    e.init_config(evidence, chars_vocab)
  File "/home/barnett/workDev/bayou/repos/github/capergroup/bayou/master/tool_files/build_scripts/out/python/bayou/experiments/low_level_evidences/evidence.py", line 30, in init_config
    self.__setattr__(attr, evidence[attr])
KeyError: 'num_layers'
```

**Comment by vijay-murali** [comment]
I'm closing this because it's just that the model file is outdated. The newly released model should not have this problem. Do re-open this if it still persists.
