### ISSUE TITLE
DriverTest test4 unit test passes on Linux, but not Mac

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#162]

**Comment by vijay-murali** [comment]
This is weird. I just ran it on my Mac and it passed all tests. Could you provide an output of the failing unit test? There are several checks in each test, and knowing which one failed might help.

**Comment by rmbarnett-rice** [comment]
Yea, its odd. Clears on my Linux laptop, but not Windows with Linux subsystem. Does clear on Carlo's Mac, but not my Mac. Here is the output I see:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running edu.rice.cs.caper.bayou.application.api_synthesis_server.servlet.ApiSynthesisResultQualityFeedbackServletTest
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.898 sec - in edu.rice.cs.caper.bayou.application.api_synthesis_server.servlet.ApiSynthesisResultQualityFeedbackServletTest
Running edu.rice.cs.caper.bayou.application.dom_driver.DriverTest
Tests run: 34, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2.24 sec <<< FAILURE! - in edu.rice.cs.caper.bayou.application.dom_driver.DriverTest
test4(edu.rice.cs.caper.bayou.application.dom_driver.DriverTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at edu.rice.cs.caper.bayou.application.dom_driver.DriverTest.testExecute(DriverTest.java:94)
        at edu.rice.cs.caper.bayou.application.dom_driver.DriverTest.testExecute(DriverTest.java:34)
        at edu.rice.cs.caper.bayou.application.dom_driver.DriverTest.test4(DriverTest.java:136)

test5(edu.rice.cs.caper.bayou.application.dom_driver.DriverTest)  Time elapsed: 0.037 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at edu.rice.cs.caper.bayou.application.dom_driver.DriverTest.testExecute(DriverTest.java:94)
        at edu.rice.cs.caper.bayou.application.dom_driver.DriverTest.testExecute(DriverTest.java:34)
        at edu.rice.cs.caper.bayou.application.dom_driver.DriverTest.test5(DriverTest.java:141)

Running edu.rice.cs.caper.bayou.application.dom_driver.FeatureTest
[0, 530 x 5, 82 x 3, 70 x 2, 582]
(seq - (loop (seq <= + / + (cond (seq - (cond (seq + >)) <)))) -)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in edu.rice.cs.caper.bayou.application.dom_driver.FeatureTest
Running edu.rice.cs.caper.bayou.core.dom_driver.VisitorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in edu.rice.cs.caper.bayou.core.dom_driver.VisitorTest
testBuildJson(edu.rice.cs.caper.bayou.core.dom_driver.VisitorTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at edu.rice.cs.caper.bayou.core.dom_driver.VisitorTest.testBuildJson(VisitorTest.java:65)

Running edu.rice.cs.caper.bayou.core.synthesizer.EvidenceExtractorTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec - in edu.rice.cs.caper.bayou.core.synthesizer.EvidenceExtractorTest
Running edu.rice.cs.caper.bayou.core.synthesizer.SynthesizerTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 23.066 sec - in edu.rice.cs.caper.bayou.core.synthesizer.SynthesizerTest

Results :

Failed tests:
  DriverTest.test4:136->testExecute:34->testExecute:94 null
  DriverTest.test5:141->testExecute:34->testExecute:94 null
  VisitorTest.testBuildJson:65 null

Tests run: 56, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by rmbarnett-rice** [comment]
FYI the same tests will pass when run from inside Intellij.

**Comment by rmbarnett-rice** [comment]
One key difference appears to be that when running the test in Maven `ast.isValid()` returns false.

https://github.com/capergroup/bayou/blob/master/src/main/java/edu/rice/cs/caper/bayou/core/dom_driver/Visitor.java#L145

**Comment by rmbarnett-rice** [comment]
When running via Maven `binding` is null:

https://github.com/capergroup/bayou/blob/master/src/main/java/edu/rice/cs/caper/bayou/core/dom_driver/DOMClassInstanceCreation.java#L47

**Comment by rmbarnett-rice** [comment]
Downgrading from OpenJDK9 to OpenJDK8 appears to resolve this issue.
