### ISSUE TITLE
Exception java.lang.UnsatisfiedLinkError: java.io.FileInputStream.available0()I

### ISSUE THREAD

**Issue by carlosmonroy** [capergroup/bayou#188]
I get the error shown below when launching `./start_bayou.sh` it seems it's related to issue  #166, even though I have the following java version

```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

```
... and here's the trace

```
Error occurred during initialization of VM
java.lang.UnsatisfiedLinkError: java.io.FileInputStream.available0()I
	at java.io.FileInputStream.available0(Native Method)
	at java.io.FileInputStream.available(FileInputStream.java:306)
	at sun.nio.cs.StreamDecoder.inReady(StreamDecoder.java:363)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:324)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at sun.misc.MetaIndex.registerDirectory(MetaIndex.java:177)
	at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:142)
	at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:138)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.Launcher$ExtClassLoader.getExtClassLoader(Launcher.java:137)
	at sun.misc.Launcher.<init>(Launcher.java:67)
	at sun.misc.Launcher.<clinit>(Launcher.java:53)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1451)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

```

**Comment by vijay-murali** [comment]
Are you running on Mac or Linux? Can you try running with version 1.8.0_152? rt_debug.jar uses this version, so perhaps there is a mismatch in some compiled class.

**Comment by vijay-murali** [comment]
This doesn't look like a bug anymore, so I'm closing it. Feel free to re-open if you encounter it again.
