### ISSUE TITLE
Multiple function/evidence crashes synthesize.sh

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#41]
The following input to `synthesize.sh`    
    
    import edu.rice.cs.caper.bayou.annotations.Evidence;

    public class TestIO1 {
        void read(String file) {
            Evidence.apicalls("readLine");
        }     
        void foo(String file) {
            Evidence.apicalls("readLine");
        }   
    }

Produces the following output:

    $ ./synthesize.sh test.java 
    Exception in thread "main" java.io.IOException: Unexpected status code: 500
	at edu.rice.cs.caper.bayou.core.bayou_services_client.ap_synthesis.ApiSynthesisClient.synthesizeHelp(ApiSynthesisClient.java:129)
	at edu.rice.cs.caper.bayou.core.bayou_services_client.ap_synthesis.ApiSynthesisClient.synthesise(ApiSynthesisClient.java:78)
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisLocalClient.synthesise(ApiSynthesisLocalClient.java:54)
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisLocalClient.main(ApiSynthesisLocalClient.java:95)

on commit f29f888707a47b6b657c49585d3bb024e8f8fd7f

**Comment by rmbarnett-rice** [comment]
Trace from logs

```java.lang.RuntimeException: Only one synthesis query at a time is supported.
	at edu.rice.cs.caper.bayou.core.synthesizer.EvidenceExtractor.visit(EvidenceExtractor.java:99) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:231) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:145) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:635) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.0.0.jar:?]
	at edu.rice.cs.caper.bayou.core.synthesizer.EvidenceExtractor.execute(EvidenceExtractor.java:76) ~[bayou-1.0.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisStrategyRemoteTensorFlowAsts.extractEvidence(ApiSynthesisStrategyRemoteTensorFlowAsts.java:264) ~[bayou-1.0.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisStrategyRemoteTensorFlowAsts.synthesiseHelp(ApiSynthesisStrategyRemoteTensorFlowAsts.java:165) ~[bayou-1.0.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisStrategyRemoteTensorFlowAsts.synthesise(ApiSynthesisStrategyRemoteTensorFlowAsts.java:138) ~[bayou-1.0.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisServlet.doPostHelp(ApiSynthesisServlet.java:194) ~[bayou-1.0.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisServlet.doPost(ApiSynthesisServlet.java:93) ~[bayou-1.0.0.jar:?]
	at edu.rice.cs.caper.servlet.SizeConstrainedPostBodyServlet.doPost(SizeConstrainedPostBodyServlet.java:176) ~[bayou-1.0.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[bayou-1.0.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:170) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126) ~[bayou-1.0.0.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [bayou-1.0.0.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [bayou-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
