### ISSUE TITLE
./synthesize.sh example_inputs/TestIO.java produces exception

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#57]
```
java.lang.IllegalArgumentException: Invalid identifier : >StackTraceElement[]<
        at org.eclipse.jdt.core.dom.SimpleName.setIdentifier(SimpleName.java:199) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.AST.newSimpleName(AST.java:2202) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.bayou.core.synthesizer.Visitor.postprocessLocal(Visitor.java:146) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.bayou.core.synthesizer.Visitor.visit(Visitor.java:96) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:231) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:145) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:635) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.bayou.core.synthesizer.Synthesizer.execute(Synthesizer.java:62) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisStrategyRemoteTensorFlowAsts.synthesiseHelp(ApiSynthesisStrategyRemoteTensorFlowAsts.java:205) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisStrategyRemoteTensorFlowAsts.synthesise(ApiSynthesisStrategyRemoteTensorFlowAsts.java:139) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisServlet.doPostHelp(ApiSynthesisServlet.java:227) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisServlet.doPost(ApiSynthesisServlet.java:93) ~[bayou-1.1.0.jar:?]
        at edu.rice.cs.caper.servlet.SizeConstrainedPostBodyServlet.doPost(SizeConstrainedPostBodyServlet.java:176) ~[bayou-1.1.0.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[bayou-1.1.0.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:170) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126) ~[bayou-1.1.0.jar:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [bayou-1.1.0.jar:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [bayou-1.1.0.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]```

**Comment by rmbarnett-rice** [comment]
@vijay-murali Can you reproduce?

**Comment by rmbarnett-rice** [comment]
Reproduced in a fresh Ubuntu container.

**Comment by rmbarnett-rice** [comment]
Introduced in f971ba5be976f119e426032610ab03f6b937728c

**Comment by vijay-murali** [comment]
This is exactly issue #48. I will be patching it soon. Please use --num_programs 5 till then to test your stuff, which gets around this issue. Moving discussion to #48 and closing this.
