### ISSUE TITLE
Intermittent NullPointerException when synthesizing TestCamera.java

### ISSUE THREAD

**Issue by rmbarnett-rice** [capergroup/bayou#71]

**Comment by rmbarnett-rice** [comment]
```
2017-09-25 17:56:51.464 | ERROR | 5634843-17 | .ApiSynthesisServlet:111   | null
java.lang.NullPointerException: null
	at edu.rice.cs.caper.bayou.core.dsl.DExcept.cleanupCatchClauses(DExcept.java:205) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.core.dsl.DSubTree.cleanupCatchClauses(DSubTree.java:135) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.core.synthesizer.DCEOptimizor.apply(DCEOptimizor.java:67) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.core.synthesizer.Visitor.visit(Visitor.java:93) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:231) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:145) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:137) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:635) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212) ~[bayou-1.1.0.jar:?]
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.core.synthesizer.Synthesizer.execute(Synthesizer.java:62) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.synthesis.ApiSynthesizerRemoteTensorFlowAsts.synthesiseHelp(ApiSynthesizerRemoteTensorFlowAsts.java:222) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.synthesis.ApiSynthesizerRemoteTensorFlowAsts.synthesise(ApiSynthesizerRemoteTensorFlowAsts.java:137) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.synthesis.ApiSynthesizerRewriteEvidenceDecorator.synthesiseHelp(ApiSynthesizerRewriteEvidenceDecorator.java:97) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.synthesis.ApiSynthesizerRewriteEvidenceDecorator.synthesise(ApiSynthesizerRewriteEvidenceDecorator.java:70) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisServlet.doPostHelp(ApiSynthesisServlet.java:241) ~[bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.bayou.application.api_synthesis_server.ApiSynthesisServlet.doPost(ApiSynthesisServlet.java:107) [bayou-1.1.0.jar:?]
	at edu.rice.cs.caper.servlet.SizeConstrainedPostBodyServlet.doPost(SizeConstrainedPostBodyServlet.java:176) [bayou-1.1.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [bayou-1.1.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:170) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [bayou-1.1.0.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [bayou-1.1.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by rmbarnett-rice** [comment]
Observed on 862ec14153f26dbc1a58534c8e20eafcb9fe0051 when running acceptance tests script.

**Comment by vijay-murali** [comment]
Since I don't have the AST which caused the issue, I'm unable to reproduce it at my end. However, looking at the code I believe I found the issue, and have committed a fix in 9d546c4. Can you re-test and confirm?

**Comment by rmbarnett-rice** [comment]
When I looked up the coordinate and saw what was going on I figured you wouldn't want / care about the motivating AST. I'll retest.

**Comment by rmbarnett-rice** [comment]
10 runs of the acceptance tests without any problems. I'm going to close.
